
remote_theme: "mmistakes/so-simple-theme@3.2.0"

title: "UCSC VLSI-DA Chip Tutorial Pages
description: "A collection of tutorial pages used by classes at UCSC."

# Footer Links
footer_links:
  - title: "Copyright 2025, Matthew Guthaus"
    url: "https://vlsida.github.io"
